const economy = require('../../Util/economy')

const Discord = require('discord.js')



module.exports = {
  commands: ['addbalance', 'addbal'],
  minArgs: 2,
  maxArgs: 2,
  expectedArgs: "<The target's @> <coin amount>",
  permissionError: 'You must be an administrator to use this command.',
  permissions: 'ADMINISTRATOR',
  description: 'Gives a user coins.',
  callback: async (message, arguments) => {
    let mention = message.mentions.users.first()

    if(!mention) mention = message.author;

    let botping = [`Bots don't use money fool..`, `Thank you for your donation but sadly I can't accept that`, `Keys.. Never heard of those`, `Nice try.....`, `Hey thats me...`]


    if(mention.id === '781466481929224203') {
      let samebot = Math.floor(Math.random() * botping.length);
      message.reply(botping [samebot]);
      return
    }


    if (!mention) {
      message.reply('Please tag a user to add coins to.')
      return
    }

    const coins = arguments[1]
    if (isNaN(coins)) {
      message.reply('Please provide a valid numnber of coins.')
      return
    }

    const guildId = message.guild.id
    const userId = mention.id

    const newCoins = await economy.addCoins(guildId, userId, coins)

    const coin = await economy.getCoins(guildId, userId)


    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${mention.username}'s balance`)
    embed.setThumbnail(mention.displayAvatarURL())
    embed.setDescription(`Keys given by ${message.author}`)
    embed.addFields({
      name: "Keys Owned Previously",
      value: `${newCoins - coins} Keys`
    },
    {
      name: "Keys Owned Currently",
      value: `${newCoins} Keys`
    })
    embed.setColor('#060103')
    embed.setFooter(`${mention.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()

    message.channel.send(embed)
  },
}