const economy = require('./../../Util/economy')
const Discord = require('discord.js')

module.exports = {
  commands: ['addbalance', 'addbal'],
  cooldown: '30',
  description: 'Adds a certain amount of coins to the mentioned users balance',
   minArgs: 2,
  maxArgs: 2,
  expectedArgs: "<The target's @> <coin amount>",
  permissionError: 'You must be an administrator to use this command.',
  permissions: 'ADMINISTRATOR',
  callback: async ( message, arguments) => {
    let mention = message.mentions.users.first()

    if (!mention) {
      message.reply('Please tag a user to add coins to.')
      return
    }

    const coins = arguments[1]
    if (isNaN(coins)) {
      message.reply('Please provide a valid numnber of coins.')
      return
    }


  
   if(!mention) mention = message.author;

    let botping = [`Are you trying to mention a bot `, `You can't mention them kiddo `, `you seriouly thought i would accept that..`, `Nice try.....`, `Hey thats me...`]


    if(mention.id === '781466481929224203') {
      let samebot = Math.floor(Math.random() * botping.length);
      message.reply(botping [samebot]);
      return
    }
    const userId = mention.id

    const newCoins = await economy.addCoins(userId, coins)

    const hi = newCoins-coins

    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${mention.username}'s balance`)
    embed.setThumbnail(mention.displayAvatarURL())
    embed.addFields({
      name: "Keys Owned Previously",
      value: `${hi} coins`,
    },
    {
      name: "Keys Owned Currently",
      value: `${newCoins}`
    })
    embed.setColor('#060103')
    embed.setDescription(`Keys given by ${message.author}`)
    embed.setFooter(`${mention.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()

    message.channel.send(embed)

    
  },
}