const economy = require('./../../Util/economy')

const Discord = require('discord.js')

module.exports = {
  commands: ['bal', 'balance'],
  cooldown: '5',
  description: 'Shows the targeted users current balance',
  maxArgs: 1,
  expectedArgs: "<The target's @>",
  permissionError: 'You must have Send messages permission to use this command',
  permissions: 'SEND_MESSAGES',
  callback: async ( message, arguments) => {

   let user = message.mentions.users.first();
   if(!user) user = message.author;

    let botping = [`Are you trying to mention a bot `, `You can't mention them kiddo `, `you seriouly thought i would accept that..`, `Nice try.....`, `Hey thats me...`]


    if(user.id === '781466481929224203') {
      let samebot = Math.floor(Math.random() * botping.length);
      message.reply(botping [samebot]);
      return
    }

    const userId = user.id

    const coins = await economy.getCoins(userId)


    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${user.username}'s balance`)
    embed.setThumbnail(user.displayAvatarURL())
    embed.addFields({
      name: "Keys Owned",
      value: `${coins} Keys`
    })
    embed.setColor('#060103')
    embed.setFooter(`${user.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp

    message.channel.send(embed)
    
  },
}