const economy = require('../../Util/economy')

const Discord = require('discord.js')

module.exports = {
  commands: ['balance', 'bal'],
  cooldown: '10',
  maxArgs: 1,
  expectedArgs: "[ Mention ]",
  description: "Shows the users current balance",
  callback: async (message) => {
    let target = message.mentions.users.first()

    if(!target) target = message.author;

    let botping = [`Bots have money ?? `, `Hahahaha... It was 10 years the last time I had a penny in my pocket and you ask how much money I have..`, `Keys.. Never heard of those`, `Nice try.....`, `Hey thats me...`]


    if(target.id === '781466481929224203') {
      let samebot = Math.floor(Math.random() * botping.length);
      message.reply(botping [samebot]);
      return
    }
    
    const guildId = message.guild.id
    const userId = target.id

    const coins = await economy.getCoins(guildId, userId)

    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${target.username}'s balance`)
    embed.setThumbnail(target.displayAvatarURL())
    embed.addFields({
      name: "Keys Owned",
      value: `${coins} Keys`
    })
    embed.setColor('#060103')
    embed.setFooter(`${target.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()

    message.channel.send(embed)
  },
}