const economy = require('../../Util/economy')

const Discord = require('discord.js')

const commonChest = require('../../Util/Common-Chest')

const RareChest = require('../../Util/Rare-Chest')

const uncommonchest = require('../../Util/Uncommon-Chest')

const epicchest = require('../../Util/Epic-Chest')

const LegendaryChest = require('../../Util/Legendary-Chest')

module.exports = {
  commands: ['chests', 'chest'],
  cooldown: '10',
  maxArgs: 1,
  expectedArgs: "[ Mention ]",
  description: "Shows the users current balance",
  callback: async (message) => {
    let target = message.mentions.users.first()

    if(!target) target = message.author;

    let botping = [`Bots have Chest ?? `, `Hahahaha... It was 10 years the last time I had a penny in my pocket and you ask how many chests I have..`, `Chests.. Never heard of those`, `Nice try.....`, `Hey thats me...`]


    if(target.id === '781466481929224203') {
      let samebot = Math.floor(Math.random() * botping.length);
      const ahaha  = (botping [samebot]);
      const me = new Discord.MessageEmbed
      me.setTitle('❌ Error Generated')
      me.setColor('#060103')
      me.setDescription(`${ahaha}`)
      me.setFooter(`Generated For ${message.author.username}`)
      me.setTimestamp()
message.channel.send(me)
      return
    }
    
    const userId = target.id

    const commonchest = await commonChest.getCommonChest(userId)

    const rarechest = await RareChest.getRareChest(userId)

    const Uncommon = await uncommonchest.getUncommonChest(userId)

    const epic = await epicchest.getEpicChest(userId)

    const legen = await LegendaryChest.getLegendaryChest(userId)

    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${target.username}'s Chests`)
    embed.setThumbnail(target.displayAvatarURL())
    embed.addFields(
    {
      name: "Common Chest Owned",
      value: `${commonchest} Chests`
    },
    {
      name: "Uncommon Chest Owned",
      value: `${Uncommon} Chests`,
    },
    {
      name: "Rare Chest Owned",
      value: `${rarechest} Chests`
    },
    {
      name: "Epic Chest Owned",
      value: `${epic} Chests`
    },
    {
      name: "Legendary Chest Owned",
      value: `${legen} Chests,`
    })
    embed.setColor('#060103')
    embed.setFooter(`${target.username}'s Chests | Generated by Rigurd`)
    embed.setTimestamp()

    message.channel.send(embed)
  },
}