const economy = require('../../Util/economy')

const Discord = require('discord.js')


module.exports = {
  commands: 'pay',
  minArgs: 2,
  maxArgs: 2,
  expectedArgs: "<Target user's @> <Amount of coins>",
  callback: async (message, arguments, text) => {
    const { guild, member } = message

    let target = message.mentions.users.first()
    

    if(!target) target = message.author;


    let botping = [`Bots don't use money fool..`, `Thank you for your donation but sadly I can't accept that`, `Keys.. Never heard of those`, `Nice try.....`, `Hey thats me...`]


    if(target.id === '781466481929224203') {
      let samebot = Math.floor(Math.random() * botping.length);
      message.reply(botping [samebot]);
      return
    }

    const coinsToGive = arguments[1]
    if (isNaN(coinsToGive)) {
      message.reply('Please provide a valid number of coins to give.')
      return
    }

    const coinsOwned = await economy.getCoins(guild.id, member.id)
    if (coinsOwned < coinsToGive) {
      message.reply(`You do not have ${coinsToGive} coins!`)
      return
    }

    const remainingCoins = await economy.addCoins(
      guild.id,
      member.id,
      coinsToGive * -1
    )
    const newBalance = await economy.addCoins(guild.id, target.id, coinsToGive)

    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${target.username}'s balance`)
    embed.setThumbnail(target.displayAvatarURL())
    embed.setDescription(`Keys given by ${message.author} who have ${remainingCoins} keys left.`)
    embed.addFields({
      name: "Keys Owned Previously",
      value: `${newBalance - coinsToGive} Keys`
    },
    {
      name: "Keys Owned Currently",
      value: `${newBalance}`
    })
    embed.setColor('#060103')
    embed.setFooter(`${target.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()

    message.channel.send(embed)
  },
}