const economy = require('../../Util/economy')

const Discord = require('discord.js')


module.exports = {
  commands: 'pay',
  minArgs: 2,
  maxArgs: 2,
  expectedArgs: "<Target user's @> <Amount of coins>",
  callback: async (message, arguments, text) => {
    const { guild, member } = message

    let target = message.mentions.users.first()

    let sameping = [`You wanna pay yourself ??`, `You can't pay yourself dummy...`, `Try mentioning someone except yourself.`]
    

    if(target === message.author) {

      let samebot = Math.floor(Math.random() * botping.length);
      const ping = (sameping [samebot]);

      const embed3 = new Discord.MessageEmbed
      embed3.color('#060103')
      embed3.description(`❌ ${ping}`)
      embed3.footer(`Generated For ${target.username}`)
      embed3.timestamp()
    }


    let botping = [`Bots don't use money fool..`, `Thank you for your donation but sadly I can't accept that`, `Keys.. Never heard of those`, `Nice try.....`, `Hey thats me...`]

    


    if(target === message.author.bot) {
      let samebot = Math.floor(Math.random() * botping.length);
      const ping = (botping [samebot]);
      const embed1 = new Discord.MessageEmbed
      embed1.color('#060103')
      embed1.description(`❌ ${ping}`)
      embed1.footer(`Generated For ${target.username}`)
      embed1.timestamp()
      message.channel.send(embed)
      return
    }

    const coinsToGive = arguments[1]
    if (isNaN(coinsToGive)) {
      message.reply(embed1)
      return
    }

    const coinsOwned = await economy.getCoins(guild.id, member.id)
    if (coinsOwned < coinsToGive) {
      const embed2 = new Discord.MessageEmbed
      embed2.color('#060103')
      embed2.description(`❌ You do not have ${coinsToGive} Keys to give ${target.username}`)
      embed2.footer(`Generated For ${message.author}`)
      embed2.timestamp()
      message.channel.send(embed2)
      return
    }

    const remainingCoins = await economy.addCoins(
      guild.id,
      member.id,
      coinsToGive * -1
    )
    const newBalance = await economy.addCoins(guild.id, target.id, coinsToGive)

    const embed = new Discord.MessageEmbed()

    embed.setTitle(`${target.username}'s balance`)
    embed.setThumbnail(target.displayAvatarURL())
    embed.setDescription(`Keys given by ${message.author} who have ${remainingCoins} keys left.`)
    embed.addFields({
      name: "Keys Owned Previously",
      value: `${newBalance - coinsToGive} Keys`
    },
    {
      name: "Keys Owned Currently",
      value: `${newBalance}`
    })
    embed.setColor('#060103')
    embed.setFooter(`${target.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()

    message.channel.send(embed)
  },
}