const Discord = require('discord.js')

const db = require("quick.db");

module.exports = {
    commands: ['bal', 'balance'],
    cooldown: '10',
    maxArgs: 1,
    expectedArgs: "[ Mention ]",
    description: "Shows the users current balance",
    callback: async (message) => {

        let user = message.mentions.members.first() || message.author;

        let bal = db.fetch(`money_${message.guild.id}_${user.id}`)
      
        if (bal === null) bal = 0;
      
        let bank = await db.fetch(`bank_${message.guild.id}_${user.id}`)
        if (bank === null) bank = 0;

        const embed = new Discord.MessageEmbed()
      
    embed.setTitle(`${user.username}'s balance`)
    embed.setThumbnail(user.displayAvatarURL())
    embed.addFields({
      name: "Keys Owned",
      value: `${bal} Keys`
    })
    embed.setColor('#060103')
    embed.setFooter(`${user.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()
        message.channel.send(embed)
      }
    }
    
