const Discord = require("discord.js");
const db = require("quick.db");
const ms = require("parse-ms");

module.exports = {
    commands: ['daily'],
    cooldown: '10',
    maxArgs: 1,
    expectedArgs: "[ Mention ]",
    description: "Shows the users current balance",
    callback: async (message) => {

        let user = message.author;

  let timeout = 86400000;
  let amount = 200;

  let daily = await db.fetch(`daily_${message.guild.id}_${user.id}`);

  if (daily !== null && timeout - (Date.now() - daily) > 0) {
    let time = ms(timeout - (Date.now() - daily));
  
    let timeEmbed = new Discord.MessageEmbed()
    .setColor("#060103")
    .setDescription(`❌ You've already collected your daily reward\n\nCollect it again in ${time.hours}h ${time.minutes}m ${time.seconds}s `)
    .setFooter(`Generated by Rigurd`)
    .setTimestamp()
    
    message.channel.send(timeEmbed)
  }
   else {
    let bal = db.fetch(`money_${message.guild.id}_${user.id}`)


    const embed = new Discord.MessageEmbed()
   embed.setTitle(`${user.username}'s balance`)
   embed.setThumbnail(user.displayAvatarURL())
   .setDescription(`Daily Rewards Claimed by ${user.username}`)
    embed.addFields(
    {
        name: "Keys Owned Currently",
        value: `${bal}`
    })
    embed.setColor('#060103')
    embed.setFooter(`${user.username}'s balance | Generated by Rigurd`)
    embed.setTimestamp()
        message.channel.send(embed)
  db.add(`money_${message.guild.id}_${user.id}`, amount)
  db.set(`daily_${message.guild.id}_${user.id}`, Date.now())




  }
}
}