const Discord = require("discord.js");
const db = require("quick.db");
const ms = require("parse-ms");

module.exports = {
    commands: ['l'],
    cooldown: '10',
    expectedArgs: "[ Mention ]",
    description: "Shows the users current balance",
    callback: async (message, arguments) => {

        let user = message.mentions.users.first() 

        let member = db.fetch(`money_${message.guild.id}_${message.author.id}`)
      
        let embed1 = new Discord.MessageEmbed()
        .setColor('#060103')
        .setDescription(`❌ You did not mention someone to pay.. Want me to do that.`);
      
        if (!user) {
            return message.channel.send(embed1)
        }
        let embed2 = new Discord.MessageEmbed()
        .setColor("#060103")
        .setDescription(`❌ You are gonna pay some amount right.. Mind specifying that.`);
        
        if (!arguments[1]) {
            return message.channel.send(embed2)
        }
        let embed3 = new Discord.MessageEmbed()
        .setColor("#060103")
        .setDescription(`❌ Hey.. That is an negative integet.`);
      
        if (message.content.includes('-')) { 
            return message.channel.send(embed3)
        }
        let embed4 = new Discord.MessageEmbed()
        .setColor("#060103")
        .setDescription(`❌ You better earn enough keys than giving others cause you dont have enough to give.`);
      
        if (member < arguments[1]) {
            return message.channel.send(embed4)
        }
      

        let bal = db.fetch(`money_${message.guild.id}_${user.id}`)

        let embed = new Discord.MessageEmbed()
        embed.setTitle(`${user.username}'s balance`)
        embed.setThumbnail(user.displayAvatarURL())
        .setDescription(`Keys Given by ${message.author} who have ${member - arguments[1]} keys left`)
         embed.addFields(
         {
             name: "Keys Owned Currently",
             value: `${bal}`
         })
         embed.setColor('#060103')
         embed.setFooter(`${user.username}'s balance | Generated by Rigurd`)
         embed.setTimestamp()
      
        message.channel.send(embed)
        db.add(`money_${message.guild.id}_${user.id}`, arguments[1])
        db.subtract(`money_${message.guild.id}_${message.author.id}`, arguments[1])
      
      }
    }