const Discord = require('discord.js')
module.exports = {
    commands: ['help', 'h', 'support', 'Help', 'HELP', 'Support', 'commands', 'Commands', 'Command','command'],
    minArgs: 0,
    maxArgs: 1,
    expectedArgs: '',
    
    callback: (message, text) => {

        const exampleEmbed = new Discord.MessageEmbed()
    .setColor('#0E1111')
	.setTitle('Support For Rigurd')
	.setAuthor('Rigurd.gg Commands Support', 'https://images.designtrends.com/wp-content/uploads/2016/02/24095354/Cool-Shipping-Company-Isometric-Logo.jpg')
    .setDescription('All the commands supported by Rigurd.gg. Type \'?help [command\' to get more info about the command')
    .addField( `**[ h , help ]**`, 'Shows all the commands', true)
    .addField(`**[ kill ] [ Mention ]**`, 'Shows a killed statement directed towards the mentioned user', false)
    .addField(`**[ rob ] [ Mention ]**`, 'Robs the mentioned user of a random amount', false)
    .addField(`**[ cm ] [ cleanmeme ]**`, 'Send a random meme from r/cleanmemes', false)
    .addField(`**[ q ] [ quote ]**`, 'Sends a random quote', false)
    .addField(`**[ ban ] [ Mention ]**`, 'Bans the mentioned member', 'Only avaible to those with required permissions', true)
    .addField(`**[ kick ] [ Mention ]**`, 'Kicks the mentioned member', 'Only avaible to those with required permissions', true)
    .addField(`**[ cool ] [ Mention ]**`, 'Tells how cool you are', true)
    .addField(`**[ cc ] [ clearchannel ]**`, 'Deletes a few messages', 'Only avaible to those with required permissions', true)
    .addField(`**[ bal ] [ balance ] [ Mention (optional) ]**`, 'Shows the targeted users balance', true)
    .addField(`**[ addbal ] [ addbalance ] [ Mention ]**`, 'Adds money to the mentioned users balance without deducting any from the sender', 'Only avaible to those with required permissions', true)
    .addField(`**[ pay ] [ Mention ]**`, 'Pays a certain amount to the mentioned user', 'Note : This command deductes money from your balance', true)
    .addField(`**[ mh ] [ math help ]**`, 'Shows all the Maths=involved commands', true)




	.setThumbnail('https://images.designtrends.com/wp-content/uploads/2016/02/24095354/Cool-Shipping-Company-Isometric-Logo.jpg')
    .setTimestamp()
    .setFooter('Generated by Rigurd.gg')
	

    message.channel.send(exampleEmbed);

    },
    permissions: 'SEND_MESSAGES',
   requiredRoles: [],
}