const Discord = require('discord.js')
module.exports = {
    commands: ['mh', 'math help'],
    minArgs: 0,
    maxArgs: 0,
    expectedArgs: '',
    
    callback: (message, text) => {
      
      const exampleEmbed = new Discord.MessageEmbed()
      .setColor('#0E1111')
     .setTitle('Support For Rigurd')
     .setAuthor('Rigurd.gg Commands Support', 'https://images.designtrends.com/wp-content/uploads/2016/02/24095354/Cool-Shipping-Company-Isometric-Logo.jpg')
      .setDescription(`All the Maths-Involved commands supported by Rigurd.gg. Type \'?help [command\' to get more info about the command
      [add, addition] ~ adds two numbers 
        [sub, subtract] ~ subtract one number from another 
        [mul, multiply] ~ Multiplies two numbers 
        [div, divide] ~ divided one number by the other 
        [expnum, exponent] ~ finds the value of a exponential number 
        [cirlgt, circlelength] ~ finds the circumference of a circle using radius 
        [cirarea, circlearea] ~ finds the area of a circle using the radius 
        [reclgt, rectanglelenght] ~ finds the perimeter of the given rectangle 
        [recarea, rectanglearea] ~ finds the area of the given rectangle 
        [sqrlgt, squarelength] ~ finds the perimeter of the given square 
        [sqrarea, squarearea] ~ finds the area of the given square 
        [trilgt, trianglelength] ~ finds the perimeter of the given triangle 
        [triarea, trianglearea] ~ finds the area of the given triangle `)

     .setThumbnail('https://images.designtrends.com/wp-content/uploads/2016/02/24095354/Cool-Shipping-Company-Isometric-Logo.jpg')
      .setTimestamp()
      .setFooter('Generated by Rigurd.gg')
     
  
      message.channel.send(exampleEmbed);
  
        
     },
     permissions: 'SEND_MESSAGES',
     requiredRoles: [],
  }